"""
Django settings for Qshop project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8&1u%oz5zbs8k-(m*6k6ecpqz_dprb#u_*-81tk6=c=la)bynt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Buyer',
    'Seller',
    'djcelery'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Qshop.shiyan.MiddleWareTest',
]

ROOT_URLCONF = 'Qshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Qshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR,"static"),
)
# STATIC_ROOT = os.path.join(BASE_DIR,"static") #静态文件的根目录，和STATICFILES_DIRS，MEDIA_URL，MEDIA_ROOT有冲突

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR,"static")


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION' : [
            "127.0.0.1:11211"      #本地memcache的地址端口
        ]
    }
}
CACHE_MIDDLEWARE_KEY_PREFIX = ''
CACHE_MIDDLEWARE_SECONDS = 600
CACHE_MIDDLEWARE_ALIAS = 'default'



alipay_public_key_string="""-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqEiOLQ+VE9irAz8xQXs3T9PYbVL+uv0Fh35Y6UgHYH10DSm/levYJbLddGxmpSsKQksL1OoSQbsGDygQQsyN5Gvd5T32ZSaLbgPG0DFlqCxtemE5ug1x0aH+S5Fh8xBa2OrO9CMZu/0uycGqCsETEcuhUXssX6qsnpLVPKTkAG4IFQlq7HyKkKypGycjOSNBGmrqGjV+fZ1sM43fc7usbxXF5fZusXj4qiy7qle59zRtzJzt0Hp9cSR7ppO/pazmPmECvZ8yuvcSSbYw6CVaB1Z37RdmhZdNE4iDTDUpkh2PSE++jAsTtxgU+iIWfq637ADH0OOTVOHc/JF2JlMUdQIDAQAB
-----END PUBLIC KEY-----"""
alipay_private_key_string="""-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAqEiOLQ+VE9irAz8xQXs3T9PYbVL+uv0Fh35Y6UgHYH10DSm/levYJbLddGxmpSsKQksL1OoSQbsGDygQQsyN5Gvd5T32ZSaLbgPG0DFlqCxtemE5ug1x0aH+S5Fh8xBa2OrO9CMZu/0uycGqCsETEcuhUXssX6qsnpLVPKTkAG4IFQlq7HyKkKypGycjOSNBGmrqGjV+fZ1sM43fc7usbxXF5fZusXj4qiy7qle59zRtzJzt0Hp9cSR7ppO/pazmPmECvZ8yuvcSSbYw6CVaB1Z37RdmhZdNE4iDTDUpkh2PSE++jAsTtxgU+iIWfq637ADH0OOTVOHc/JF2JlMUdQIDAQABAoIBAQCjT0YqlKSnzeyoCftTALB816mA7rol3MYw53yBZ1VBXn3xCELUyzvH2fzvrwMt5sbd7tZcmYt+HnGS495j9P7+XW/JuIgVQYKuERwvjsCIpBTaXuAWnlWGix6tVzknGQgQ2k5cvnOK6/kr8rWCGjzXWDYFTPOTI57BhN1LLPnXL1y5frlNTnPcxyC4Ayj5ab5btdF8MkgQVOOcd8ooPxXi3hPJkX1l4wlrjFkquHH+OF+e9qr6JtEIEodeHL5bVZu4y2nWXk76sAI3xRFM/rdcRFSDKouAErxJiZwHyq0CrDp8xyh44xZPG9H+fiw197BdWomNhHI7ujjq4m4ypS4BAoGBAOA+Kkb1lZSbpVWTio/19RFQ7z8eXTZfSq/QVpwyHNkC+iKG3e5lO8MWeV6Hbh/SoZ9Wj7GJkqAfpL6T3CSNtcWT9xgfDftV93E9cZlM2FTdKKFWOHRHu93NRZGYRa5dLACR+/11Jmq6uZ1ecVceUUfShNcrJlEdxva6O2tQwro5AoGBAMAdmpreE3VM1FRe1EeJ8qXAIL4q6G36Ay7TS3VcgOLe/HDI40bSMdAVk8mgTDcxmv6KUCyPOPd4Yj6VgI5PNOz09o+cibljEg+IBS8CN0yK/k5ZDFr7ViLX+wxsnWnDr9Bd1Nwz5GfdtHCs8xp9RBoqkkKI9ZyivGb6rMGGE9wdAoGBALQhm8p2mprO0OhGZccw95TaY+VbGduEfrVucTR1mPDGUHKNzhcjoPccxZAm0FKl24joevNNpMgVwzwIAI4oe7zkGFh7Ebs1GlkP14Ii1aCOK4Y2gZD+0q3gqCLFpCvl0mP+4OKAScTwjAwbAobN5tMADA/gLJ56ggpOHU8eh94ZAoGAfOSB9r36bl5VBshjPmKqsSB26MniMmS/HvjT7GcHjvWhrPyb7BWHtpvgaMph4dvIxENMnbs6MH89dywf1+QcJxOVGoWMb029lwU5QXcyVftiGbMAOkF8nMhF96zApNpHeLEXSVQe33sc68czf3wCAvS8Aq8g5QRScKv0FRdB3+0CgYAPHbICLemEJ84+aCwV7FQ9v7I4nLqtgsmb7De3SxqNvPNBr5BYUcSWc+Ig6PpREYDVuBwL3dfzBAkT225CvNZWqlrpXy31TFTqGEIsQ2UFW9R0JGXfYxWhdLnyxz3WKau31fJjaUOimPoTINzRlgr2758SJimAty12PPyB7s6Clw==
-----END RSA PRIVATE KEY-----"""


DING_URL="https://oapi.dingtalk.com/robot/send?access_token=43f4b33c22ae840d54ee6de90c43b6dbdd12c45b2a07686ec5820e806dd913d2"

import djcelery
djcelery.setup_loader()
BROKER_URL='redis://127.0.0.1:6379/1'
CELERY_IMPORTS=('CeleryTask.tasks')
CELERY_TIMEZONE='Asia/Shanghai'
CELERY_SCHEDULER='djcelery.schedulers.DatabaseScheduler'









