# Generated by Django 2.1.8 on 2019-09-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cat_user',
            new_name='cart_user',
        ),
    ]
